CREATE TABLE IF NOT EXISTS PROJECTS
(
    PROJECT_ID  INT AUTO_INCREMENT PRIMARY KEY,
    NAME        VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    START_DATE  DATE         NOT NULL,
    END_DATE    DATE         NOT NULL
    );

CREATE TABLE IF NOT EXISTS SUBPROJECTS
(
    SUBPROJECT_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME          VARCHAR(255) NOT NULL,
    DESCRIPTION   VARCHAR(255) NOT NULL,
    START_DATE    DATE         NOT NULL,
    END_DATE      DATE         NOT NULL,
    PROJECT_ID    INT,
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS (PROJECT_ID)
    );

CREATE TABLE IF NOT EXISTS EMPLOYEES
(
    EMPLOYEE_ID        INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME         VARCHAR(255) NOT NULL,
    LAST_NAME          VARCHAR(255) NOT NULL,
    EMAIL              VARCHAR(255) NOT NULL,
    PASSWORD           VARCHAR(255) NOT NULL,
    ROLE               VARCHAR(255) NOT NULL,
    IS_PROJECT_MANAGER BOOLEAN
    );

CREATE TABLE IF NOT EXISTS TASKS
(
    TASK_ID         INT AUTO_INCREMENT PRIMARY KEY,
    NAME            VARCHAR(255) NOT NULL,
    DESCRIPTION     VARCHAR(255) NOT NULL,
    ESTIMATED_HOURS INT          NOT NULL,
    PRIORITY        INT,
    DEADLINE        DATE         NOT NULL,
    EMPLOYEE_ID     INT,
    SUBPROJECT_ID   INT,
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID),
    FOREIGN KEY (SUBPROJECT_ID) REFERENCES SUBPROJECTS (SUBPROJECT_ID)
    );

-- Junction table
CREATE TABLE IF NOT EXISTS PROJECT_EMPLOYEE
(
    PROJECT_ID  INT,
    EMPLOYEE_ID INT,
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS (PROJECT_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID),
    PRIMARY KEY (PROJECT_ID, EMPLOYEE_ID)
    );

