name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - deployment
  pull_request:
    branches:
      - feature

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: azul

      - name: Build with Maven
        env:
          PROD_DB_URL: ${{secrets.PROD_DB_URL}}
          PROD_DB_USER: ${{secrets.PROD_DB_USER}}
          PROD_DB_PASSWORD: ${{secrets.PROD_DB_PASSWORD}}
        run: mvn clean package

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-app
          path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/deployment'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          # Replace with name of app-name:
          app-name: your-azure-app-name
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
