name: CI Pipeline

on:
  push:
    branches:
      - 'feature/*'   # Trigger on push to any feature branch
  pull_request:
    branches:
      - 'main'        # Trigger for PRs to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 21 (Adoptium)
        uses: actions/setup-java@v2
        with:
          java-version: '21'           
          distribution: 'adoptium'  # Only use 'adoptium' here

      - name: Build with Maven
        env:
          PROD_DB_URL: ${{ secrets.PROD_DB_URL }}
          PROD_DB_USER: ${{ secrets.PROD_DB_USER }}
          PROD_DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
        run: mvn clean install

      - name: Run tests
        run: mvn test
